### Input

In [17]:
input = """4
3 2 1 2"""

output = """1 2 2 3"""

In [18]:
input = """3
2 3 8"""

output = """2 3 8"""

In [19]:
def line_generator(input):
    """Yields all lines in stdin"""
        
    for line in input:
        yield line

line = line_generator(input.split('\n'))
output = [int(out) for out in output.split()]

### Read Input and Convert to `int`

In [20]:
n = next(line)
col_heights = next(line)

n = int(n.strip())
col_heights = [int(col_str) for col_str in col_heights.split()]

### Transform Input

In [21]:
box = np.zeros([max(col_heights), n])

box

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [22]:
for c, col_height in enumerate(col_heights):
    box[-col_height:, c] = 1

box

array([[ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### Tip Sideways

In [23]:
for i, row in enumerate(box):
    num_zeros = np.sum(row == 0)
    box[i, :num_zeros], box[i, num_zeros:] = 0, 1
    
box

array([[ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### Count Number of Columns

In [24]:
new_col_heights = box.sum(axis=0, dtype=np.int)

new_col_heights

array([2, 3, 8])

### Assert Correct

In [25]:
assert np.all(new_col_heights == output)