### Input

In [107]:
input = (
    '4',
    '3 2 1 2'
)

output = (1, 2, 2, 3)

In [108]:
input = (
    '3',
    '2 3 8'
)

output = (2, 3, 8)

In [109]:
def line_generator():
    """Yields all lines in stdin"""
        
    for line in input:
        yield line

line = line_generator()

### Read Input and Convert to `int`

In [110]:
n = next(line)
col_heights = next(line)

n = int(n.strip())
col_heights = [int(col_str) for col_str in col_heights.split()]

### Transform Input

In [111]:
box = np.zeros([max(col_heights), n])

box

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [112]:
for c, col_height in enumerate(col_heights):
    box[-col_height:, c] = 1

box

array([[ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### Tip Sideways

In [113]:
for i, row in enumerate(box):
    num_zeros = np.sum(row == 0)
    box[i, :num_zeros], box[i, num_zeros:] = 0, 1
    
box

array([[ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### Count Number of Columns

In [114]:
new_col_heights = box.sum(axis=0, dtype=np.int)

new_col_heights

array([2, 3, 8])

### Assert Correct

In [115]:
assert np.all(new_col_heights == output)